var m = new Array(
"Show the",
"Hide the",
"Display",
"Select",
"__none__",
"Add to  (+)",
"Subtract  (-)",
"Multiply by  (*)",
"Divide by (/)",
"less than",
"from",
"to",
"and greater",
"Click to open URL.",
"Additional Metadata",
"Reposition the ",
", and press left mouse button",
"Legend",
"Annotation",
"UTM Zone",
"lat",
"lon",
"Click on the map to pan or zoom",
"All Selected",
"None Selected",
"Click on map objects to open URLs",
"Click on the map to pan or zoom",
"Cannot zoom that far in",
"Cannot zoom that far out",
"recenter and zoom out",
"Add   :",
"Reduce:",
"Composite Selection",
"Invalid formula.",
"Select a varaible first, then evaluate a query",
"Check the formula and evaluate it again.",
"Here are examples of valid formulas:",
"Second variable:",
"[Current var] &gt;= 500",
"[Current var] &lt;&gt; 1000",
"Selection Information:",
"Currently selected",
"records.",
"Query expression:",
"No variable is currently active.",
"Select a variable from the list,",
"or compose it using the Compose button.",
"Once a variable is mapped in the right frame, you can query it.",
"The current variable is",
"Minimum value is",
"Maximum value is",
"Range is",
"Number of objects is",
"Click on a variable name to map it in the right frame",
"Map Navigation",
"Select this option if you want to",
" by clicking on the map",
"recenter and zoom in",
"recenter",
"open URLs associated with map objects",
"Return to the original map extent",
"Initial View",
"Open the Help window",
"Help",
"Edit",
"Application of XML for Interactive Online Mapping",
"AxioMap",
"Current variable",
"... click and enter value...",
"... enter value now...",
"Compose Variable",
"Select an operation here, if you want to map a derived variable",
"Operation:",
"Toggle the LEGEND display on or off",
"Select a second variable",
"[Current var]",
"Build Query",
"Construct a query expression here, by clicking in an operation and typing a numeric value",
"greater than or equal to",
"equal to",
"less than or equal to",
"not equal to",
"Display information about the current variable",
"Info",
"Evaluate the query and map the results",
"Evaluate",
"Reset the query expression window",
"Clear",
"New Set",
"Add to Set",
"Select from Set",
"Select All",
"Unselect All",
"Listing",
"List selected records",
"Options",
"Classification",
"Equal Intervals",
"Divide range of values into equal intervals",
"Quantiles",
"Group objects into groups of equal size",
"Select number of intervals for thematic mapping",
"Intervals",
"Toggle the",
"Toggle the ANNOTATION display on or off",
"Toggle the display of area LABELS on or off",
"Labels",
"Set the zooming level",
"Zoom level",
"Circle (ALT-click)",
"100 ft,200 ft,300 ft,500 ft,750 ft,1000 ft,1/4 mi,1/2 mi,3/4 mi,1 mi,2 mi,3 mi,5 mi,7.5 mi,10 mi,15 mi,20 mi,30 mi,50 mi,100 mi",
"red,maroon,purple,blue,navy,aqua,black,silver,white,green,lime,olive,yellow",
"layer display on or off",
"Expand or collapse the",
"category",
"Open table of",
"dialog",
"Loading",
"Map Project",
". Please Wait...",
"Error opening",
"XML file",
"Background",
"Outline",
"Line",
"Polygon",
"Point",
"Thematic",
"Attribute Data",
"Messages",
"Layer",
"NAME",
"Selected Records",
"Select a Dataset",
"Specify the radius of a circle",
"Select a circle color",
"100,200,300,500,750,1000,1320,2640,3960,5280,10560,15840,26400,39600,52800,79200,105600,158400,264000,528000",
"0 or missing data",
"Axiomap: Selected Records",
"Axiomap: List of records for point layer",
"Name",
"Compose",
"Query",
"Options",
"zoom",
"x",
"pan",
"IN",
"OUT",
"open URL",
"in grayscale",
"Switch between color and grayscale thematic map",
"this is #152")

